runtime: go112

handlers:
  - url: /
    static_files: front/dist/index.html
    upload: front/dist/index.html
  - url: /css
    static_dir: front/dist/css
  - url: /js
    static_dir: front/dist/js
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
