runtime: go112

default_expiration: "1d"

env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.80
  target_throughput_utilization: 0.70
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 60

handlers:
  - url: /ads.txt
    static_files: front/dist/ads.txt
    upload: front/dist/ads.txt
  - url: /favicon.ico
    static_files: front/public/favicon.ico
    upload: front/public/favicon.ico
  - url: /css
    static_dir: front/dist/css
  - url: /js
    static_dir: front/dist/js
  - url: /img
    static_dir: front/public/img

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
