runtime: go116

default_expiration: "3d"

env: standard
instance_class: F1


handlers:
  - url: /ads.txt
    static_files: front/dist/ads.txt
    upload: front/dist/ads.txt
  - url: /robots.txt
    static_files: front/public/robots.txt
    upload: front/public/robots.txt
  - url: /app-ads.txt
    static_files: front/public/app-ads.txt
    upload: front/public/app-ads.txt
  - url: /rss.xml
    static_files: front/public/rss.xml
    upload: front/public/rss.xml
  - url: /favicon.ico
    static_files: front/public/favicon.ico
    upload: front/public/favicon.ico
  - url: /css
    static_dir: front/dist/css
  - url: /js
    static_dir: front/dist/js
  - url: /img
    static_dir: front/public/img

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  ENV: 'prd'
