runtime: go112

handlers:
  - url: /ads.txt
    static_files: front/dist/ads.txt
    upload: front/dist/ads.txt
  - url: /favicon.ico
    static_files: front/public/favicon.ico
    upload: front/public/favicon.ico
  - url: /css
    static_dir: front/dist/css
  - url: /js
    static_dir: front/dist/js
  - url: /img
    static_dir: front/public/img

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
