version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          command: sudo apt-get update && sudo apt-get install libxtst6 libnss3-dev -y
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "front/yarn.lock" }}
          working_directory: front
      - run:
          command: yarn install --frozen-lockfile
          working_directory: front
      - run:
          command: yarn build
          working_directory: front
      - run:
          command: sudo npm install -g css-optimization puppeteer --unsafe-perm=true
          working_directory: front
      - run:
          command: css-optimization -p . -i . -c dist/css
          working_directory: front

      - save_cache:
          key: yarn-packages-{{ checksum "front/yarn.lock" }}
          paths:
            - ~/.cache/yarn
          working_directory: front
      - persist_to_workspace:
          root: front/dist
          paths:
            - ./*
  deploy:
    working_directory: ~/pistatium/my_site
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - attach_workspace:
          at: front/dist
      - run: echo $GOOGLE_API_KEY > key.json
      - run: gcloud auth activate-service-account $ACCOUNT --key-file key.json
      - run: rm key.json
      - run: gcloud --quiet --project kimihiro-n app deploy --no-promote

workflows:
  version: 2
  ga-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
